### ISSUE TITLE
Adding a customised loader to the page.

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/wiki#10]
We need an anime inspired loader on the page

**Comment by ArunTeltia** [comment]
Do we tho ? I think our Boot animation will look awesome before the page load 
What do you think @LordShenron

**Comment by LordShenron** [comment]
After our recent talk on whatsapp this goes way wayyy away from what we have to do.

**Comment by ArunTeltia** [comment]
YUP I totally forget about it XD
