### ISSUE TITLE
Update embedded form UI 

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/wiki#19]
**Description**

Update and fix embedded form UI  color and spacing.

**Screenshot**

![image_2021_04_29T15_27_20_058Z](https://user-images.githubusercontent.com/54466041/116577290-f725bc80-a92d-11eb-9af6-8c463884b7d0.png)

**Comment by Samridhi-98** [comment]
@ArunTeltia I would like to work on this issue please assign it to me.

**Comment by LordShenron** [comment]
I am assigning this issue to you. This one seems pretty legit so Thanks for working on it.
