### ISSUE TITLE
Changing the color of on hover navigation menu

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/wiki#20]
**Description**
The colour of on hover menu doesn't match the website theme.

**Screenshot**
![image](https://user-images.githubusercontent.com/22374829/116578086-aebace80-a92e-11eb-959d-6aff8f9acf14.png)

**Comment by ritik307** [comment]
@ArunTeltia I would like to work on this issue plz assign

**Comment by ArunTeltia** [comment]
GO for it @ritik307

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia Plz review

**Comment by ritik307** [comment]
@ArunTeltia  @LordShenron plz provide the `gssoc21` and appropriate `level` tag to the **issue** also
