### ISSUE TITLE
404 page Alignment issue 

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/wiki#22]
**Describe the feature**
There is an alignment issue on the `components\404page\404page.js`

**Screenshots**
![404](https://user-images.githubusercontent.com/22374829/116738449-1268f880-aa10-11eb-8bfe-e1f93e751ce1.PNG)

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@ArunTeltia @LordShenron I would like to work on this issue plz assign

**Comment by ArunTeltia** [comment]
Go ahead @ritik307 assigning this one to you

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia Kindly add `gssoc` and `level` tag to the issue
