### ISSUE TITLE
Inappropriate footer alignment 

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/wiki#24]
**Description**
Footer is not aligned to the center of the viewport.

**Screenshot**
![footer](https://user-images.githubusercontent.com/54466041/116739314-26f9c080-aa11-11eb-9f10-4fdeb0b30378.PNG)

**Comment by Samridhi-98** [comment]
@ArunTeltia  @LordShenron  I would like to fix this please assign it to me.

**Comment by LordShenron** [comment]
Go ahead with it.
