### ISSUE TITLE
Add responsiveness to different viewports 

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/wiki#27]
**Description**
The website is not responsive to different viewports as shown below:

https://user-images.githubusercontent.com/22374829/116925417-ccfa3480-ac76-11eb-9f55-eecc548c1048.mp4

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia I would like to work on this issue plz assign.

**Comment by LordShenron** [comment]
Assigning this to you.
