### ISSUE TITLE
Add prettier and eslint 

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/wiki#29]
**Description**
Define linting rules so that all the files are properly linted.

**Requirements**
- [ ]  Add .eslintrc.json and .eslintignore and add the linting rules
- [ ] Add .prettierrc and .prettierignore and add the linting rules
- [ ] Add eslint and prettier as devDependencies in package.json
- [ ] Add linting scripts to package.json

**Comment by Samridhi-98** [comment]
@ArunTeltia  @LordShenron I would like to work on it please assign it to me.

**Comment by ArunTeltia** [comment]
if we add this now, not gonna lie that will be a lot of work because of all the issues tha we are discarding in the current app but yes lets give it a shot, want to work on this @Samridhi-98

**Comment by Samridhi-98** [comment]
> if we add this now, not gonna lie that will be a lot of work because of all the issues tha we are discarding in the current app but yes lets give it a shot, want to work on this @Samridhi-98

Yes, I would like to work on this if it seems useful to you and LordShenron for the project.

**Comment by LordShenron** [comment]
Assigned this to you samridhi.. good luck with it :)

**Comment by ArunTeltia** [comment]
Will advice to break this issue into many prs because it will have a lot of work

**Comment by Samridhi-98** [comment]
> Will advice to break this issue into many prs because it will have a lot of work

Okay.
