### ISSUE TITLE
Refactoring side-nav

### ISSUE THREAD

**Issue by FireQueen-3010** [ProjectSakura/wiki#4]
![image](https://user-images.githubusercontent.com/59244300/113105834-a97b3e80-921f-11eb-8529-3a5d3e0d56f3.png)

**Comment by LordShenron** [comment]
> ![image](https://user-images.githubusercontent.com/59244300/113105209-f6aae080-921e-11eb-8f5b-e8ce691243b1.png)

Bruh not this LMAO

**Comment by LordShenron** [comment]
![image](https://user-images.githubusercontent.com/30292727/113105687-7cc72700-921f-11eb-971a-64427c41cf2c.png)
this sidenav

**Comment by FireQueen-3010** [comment]
Okay my bad :p

**Comment by FireQueen-3010** [comment]
I am thinking I'll make the headings as sub-drawers as displaying everything by default looks kinda crowded. What do you suggest @LordShenron @ArunTeltia ?

**Comment by LordShenron** [comment]
> I am thinking I'll make the headings as sub-drawers as displaying everything by default looks kinda crowded. What do you suggest @LordShenron @ArunTeltia ?

That would be better.. Also collapsing the already opened sub drawer when opening a new sub drawer will look  pretty neat. 
I have pushed my initial changes in https://github.com/ProjectSakura/wiki-redesign/commit/ac887c8727582f6327f2e14e467a359f3e49a75b  commit.. you can take up from here.

**Comment by FireQueen-3010** [comment]
> > I am thinking I'll make the headings as sub-drawers as displaying everything by default looks kinda crowded. What do you suggest @LordShenron @ArunTeltia ?
> 
> That would be better.. Also collapsing the already opened sub drawer when opening a new sub drawer will look pretty neat.
> I have pushed my initial changes in [ac887c8](https://github.com/ProjectSakura/wiki-redesign/commit/ac887c8727582f6327f2e14e467a359f3e49a75b) commit.. you can take up from here.

Yeah true ... okay

**Comment by ArunTeltia** [comment]
I am not sure if i understand this issue if any of you can explain me that would be awesome guys

**Comment by ArunTeltia** [comment]
And for making commit history a little zesky lets use some emojis in the commit message @FireQueen-3010 @LordShenron XD

**Comment by LordShenron** [comment]
> I am not sure if i understand this issue if any of you can explain me that would be awesome guys

topnames (which are basically headings and are not buttons ) are mixing up with normal elements in sidenav.

**Comment by ArunTeltia** [comment]
HMMM okay let me know if there is some work for me first delete all the extra things from the navbar and then start creating components @LordShenron

**Comment by LordShenron** [comment]
> HMMM okay let me know if there is some work for me first delete all the extra things from the navbar and then start creating components @LordShenron

I am trying to deploy but uhh it's a pain in the ass.

**Comment by ArunTeltia** [comment]
🤣🤣
![46mhne](https://user-images.githubusercontent.com/43555219/113126399-37155900-9235-11eb-8976-c136caa3beb0.png)

**Comment by FireQueen-3010** [comment]
> > HMMM okay let me know if there is some work for me first delete all the extra things from the navbar and then start creating components @LordShenron
> 
> I am trying to deploy but uhh it's a pain in the ass.

Deploy what? Maybe I can help? I kinda have an idea about backend

**Comment by ArunTeltia** [comment]
website to github pages its totally different thing @FireQueen-3010

**Comment by LordShenron** [comment]
> > > HMMM okay let me know if there is some work for me first delete all the extra things from the navbar and then start creating components @LordShenron
> > 
> > 
> > I am trying to deploy but uhh it's a pain in the ass.
> 
> Deploy what? Maybe I can help? I kinda have an idea about backend

There is no backend on github pages.. we do everything on static pages.

**Comment by ArunTeltia** [comment]
I dont understand why tf we are deploying right now ?

**Comment by LordShenron** [comment]
> I dont understand why tf we are deploying right now ?

Coz why not? we will know how it works with github pages in a early stage then

**Comment by FireQueen-3010** [comment]
> > > > HMMM okay let me know if there is some work for me first delete all the extra things from the navbar and then start creating components @LordShenron
> > > 
> > > 
> > > I am trying to deploy but uhh it's a pain in the ass.
> > 
> > 
> > Deploy what? Maybe I can help? I kinda have an idea about backend
> 
> There is no backend on github pages.. we do everything on static pages.

Okay

**Comment by FireQueen-3010** [comment]
I ran mine usually as I do.. and only this time it happened so

**Comment by ArunTeltia** [comment]
Should this be closed after #6 got merged

**Comment by LordShenron** [comment]
> Should this be closed after #6 got merged

No

**Comment by ArunTeltia** [comment]
Is there something remaining in this?

**Comment by FireQueen-3010** [comment]
@ArunTeltia , actually this a different issue and I have not completed this yet . I'll do this one today :)

**Comment by FireQueen-3010** [comment]
This is for persistent drawer left

**Comment by ArunTeltia** [comment]
Okay i don't understand of this pr but it sounds like it is important. 
Let me know if you have some problems

**Comment by LordShenron** [comment]
> Okay i don't understand of this pr but it sounds like it is important.
> Let me know if you have some problems

Get your ass to designing the new  download page.

**Comment by ArunTeltia** [comment]
Will do

**Comment by FireQueen-3010** [comment]
https://user-images.githubusercontent.com/59244300/113478537-08061e00-94a7-11eb-8276-68bff365b57a.mp4

![image](https://user-images.githubusercontent.com/59244300/113478547-0e949580-94a7-11eb-9b6f-abd87842ee8f.png)

Hi, @LordShenron , this is how it looks after changing the headings to subdrawers (I haven't done any styling yet). Do you think we should proceed with is or does it make the side-nav look empty , Please suggest @LordShenron

**Comment by LordShenron** [comment]
> bandicam.2021-04-03.16-51-40-264.mp4
> 
> Hi, @LordShenron , this is how it looks after changing the headings to subdrawers (I haven't done any styling yet). Do you think we should proceed with is or does it make the side-nav look empty , Please suggest @LordShenron

I don't feel doing this is a good idea.

**Comment by FireQueen-3010** [comment]
Okay cool
