### ISSUE TITLE
Add Meta Tags for SEO 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/wiki#9]
Right now website has different logos(title), unminified images and the link data is create react app change it to the description og the project

**Comment by FireQueen-3010** [comment]
Please assign this to me :) @ArunTeltia

**Comment by ArunTeltia** [comment]
Do we need some meta-words as well for proper seo?
It is ambiguous will see if we need or not for now lets not close this issue

**Comment by LordShenron** [comment]
> Do we need some meta-words as well for proper seo?
> It is ambiguous will see if we need or not for now lets not close this issue

Just refer to index.html or download.html in main page. It have everything.

**Comment by ArunTeltia** [comment]
For now I dont think any need of this issue as main meta tags have been added in the #12 pr 
For that reason I am closing this
